---
jobs:
- name: CD-Build
  public: true
  serial: true
  plan:
  - get: citytest-concourse
  - get: citytest
    trigger: true
  - { task: build-gradle, file: citytest-concourse/task_gradle_build.yml }
  - put: build_artifact
    params:
      from: build-gradle/build/libs/cities-0.0.1-SNAPSHOT.jar
  - put: build_manifest
    params:
      from: build-gradle/manifest.yml

- name: CD-Deploy
  plan:
  - get: build_artifact
    trigger: true
    passed: [CD-Build]
  - get: build_manifest
    trigger: true
    passed: [CD-Build]
  - put: resource-deploy-web-app
    params:
      manifest: build_manifest/manifest.yml
      path: build_artifact/cities-0.0.1.jar

resources:
- name: citytest-concourse
  type: git
  source:
    uri: https://github.com/rgadhia/citytest-concourse

- name: citytest
  type: git
  source:
    uri: https://github.com/rgadhia/citytest

- name: build_artifact
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: rgadhia-citytest-artifacts
    region_name: us-east-1
    versioned_file: cities-0.0.1.jar

- name: build_manifest
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: rgadhia-citytest-artifacts
    region_name: us-east-1
    versioned_file: manifest.yml

- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{pcf-username}}
    password: {{pcf-password}}
    organization: Northwest
    space: rgadhia
    skip_cert_check: false